spring:
  mail:
    #右键发送服务器地址
    host: smtp.qq.com
    #右键发送人的账号
    username: 2892379404@qq.com
    #右键服务的第三方授权码，不是qq密码
    password: tpiveuzagfiddhed
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          debug: true
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 10MB
      #所含有的文件大小
      max-request-size: 100MB
      enabled: true

